baseurl: '/'
permalink: pretty
title: '1st FRAME Workshop'

google_analytics_id: ""

homepage:
  show_call_box: false
  show_social_buttons: true

seo:
  meta_og_title: "1st FRAME Workshop"
  meta_og_type: "website"
  meta_og_url: "https://remaplab.github.io/frame2026/"
  meta_og_description: "The **FRAME Workshop** is a novel workshop aimed at piloting a new paradigm for recommender systems research execution and evaluation. The workshop will foster the identification and formalization of new recommendation tasks beyond the saturated top-N setting, with shared and rigorous evaluation methodologies."


collections:
  services:
    output: true
  editions:
    output: true
  team:
    output: true
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/

  talks:
    # Talk categories
    main_categories:
      - name: Keynote
        color: info
      - name: Session
        color: warning
      - name: Breaks
        color: success
      - name: Closing
        color: danger

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
